backend/config/config.ts, backend/controllers/WebhookController.ts, backend/docker-compose.yaml, backend/environment/env.social-app-backend.docker.template, backend/environment/env.social-app-backend.template, backend/index.ts
- add API_PORT to the Config class
- add PRIVATE_IP env var to support binding to a different interface for internal webhooks
- add PRIVATE_PORT env var to support specifying the port for the private api/webhooks API
- add basic/sample WebhooksController bound to the new private API app instance
The goal of this PR is to establish basic scaffolding for the "internal" API of the Gateway; that is, the API that supports webhooks being called from other backend services. We want the ability to have this API accessible on a different network address than the public-facing API, in order to support various network/security deployment configurations.
Related to #25, #33
=> feat: add private api and webhook controller scaffolding

frontend/src/chrome/UserAvatar.tsx, frontend/src/dsnpLink.ts, frontend/src/login/LoginScreen.tsx, frontend/src/service/AuthService.ts
The goal of this PR is to allow the user to specify a URL for the social-gateway-backend in the environment that will override the value generated from the OpenAPI spec document.
=> feat: allow env override of backend URL

backend/ENVIRONMENT.md, backend/config/config.ts, backend/controllers/AuthController.ts, backend/environment/env.social-app-backend.docker.template, backend/environment/env.social-app-backend.template, backend/services/feed.ts, backend/utils/url-transation.ts
The goal of this PR is to allow both the SAT frontend & backend properly resolve message content retrieved from the chain by rewriting the embedded content URL as appropriate.
Closes #55
=> fix: message content from chain properly resolved in both BE and FE

backend/package-lock.json, backend/services/feed.ts, frontend/package-lock.json
The goal of this PR is to fix posts not showing correctly.
`fetchAndCachePosts` was getting out of sync. 
In the case where `fetchAndCachePosts` is called for a block, but it executes before the `content-watcher` sends the webhook notification, it would cache an empty block. 
Then the announcement comes from `content-watcher`, the cache skips the block because it thinks it is already in the cache.
`fetchAndCachePosts` was modified so that empty blocks are not cached.
Developed with help from:
@JoeCap08055 @saraswatpuneet 
- `fetchAndCachePosts` was modified so that empty blocks are not cached.
- `npm audit fix` was used to update `package-lock.json` to fix vulnerabilites.
1. Startup SAT Backend and Frontend
2. Create a new post and wait about 30-60 seconds (for content-watcher interval) …
=> fix: Do not cache empty blocks in fetchAndCachePosts

docker-compose.yaml, frontend/src/login/Login.tsx, start-gateway.sh
The goal of this PR is to update the `start-gateway.sh` script to allow editing the IPFS environment variables.
Add a new path to the script which first asks the user if they would like to change the IPFS settings and then collects the settings and saves them in the `.env-saved` file.
- `docker-compose.yaml` updated `pull_policy` to `always` to ensure that the latest published micro-service container is always pulled.
- `start-gateway.sh` updated as per solution.
- `/frontend/Login.tsx` updated to increase account creation timeout to 90 seconds to allow for block finalization delay on testnet.
1. Execute `start-gateway.sh` and verify that IPFS values are able to be changed.
2. `rm .env-saved` to go through the questions again.
=> Update startup script and docker-compose files for testnet connection

frontend/src/App.tsx, frontend/src/chrome/Header.tsx
The goal of this PR is make sure that on login we're always redirected to the explore page ('/').
Closes #82 
On call of login() navigate to '/'
* add navigate call
1. on login, you always land on the home page.
=> navigate to explore on login

frontend/src/App.tsx, frontend/src/Feed.tsx, frontend/src/PageRoutes.tsx, frontend/src/chrome/LoginModal.module.css, frontend/src/chrome/LoginModal.tsx, frontend/src/content/FromTitle.tsx, frontend/src/content/Post.tsx, frontend/src/content/PostList.tsx, frontend/src/login/Login.tsx, frontend/src/login/LoginScreen.tsx
The goal of this PR is to better handle navigation and login errors when not logged in.
Closes #106 
- When login is canceled, stop loading and don't throw error.
- If user tries to click on a profile while not logged in, a login modal opens.
* Implemented above solutions
1. Logout
2. Try to click on user through the avatar in a post
3. see login modal pop up
4. login through modal
5. should be able to navigate everywhere
6. logout
7. login through header button
=> 106 fix navigation bugs when not logged in

backend/controllers/GraphController.ts, frontend/src/chrome/Profile.module.css, frontend/src/chrome/Profile.tsx, frontend/src/chrome/ProfilePage.tsx, frontend/src/content/NewPostModal.tsx, frontend/src/content/Post.module.css, frontend/src/network/Connections.tsx, frontend/src/network/ConnectionsList.module.css, frontend/src/network/ConnectionsList.tsx, frontend/src/network/ConnectionsListProfiles.module.css, frontend/src/network/ConnectionsListProfiles.tsx, frontend/src/network/ConnectionsModal.module.css, frontend/src/network/ConnectionsModal.tsx, frontend/src/network/GraphChangeButton.tsx, frontend/src/types.ts
The goal of this PR is to create a modal and add a followers section to profile.
Closes #79 
After exploring how to solve this ticket and talking with @enddynayn and @JoeCap08055 we decided to keep the followers section in the modal but instruct the user on what they need to do in order to get a list of followes, since it is not something that we store in a user's graph.
* Added modal
* Added styling
* Changed profile UI for how we display followers and following count.
1. Check that following displays the correct number of users and user profiles.
2. Follow/Unfollow and watch it update.
3. Note: The spinner UI for follow/unfollow is not yet connected to the webhook, so it's a little buggy, but @JoeCap08055 created a ticket to add this. …
=> 79 add followers section to profile

frontend/src/content/PostList.tsx
The goal of this PR is to see discover posts before and after login
Closes #109 
Check to see what is causing the rerender and fix the bug.
* Removed network from the useEffect that gets posts.
1. Logout
2. See feed
3. login
4. still see feed
=> discover posts persist

backend/index.ts, backend/openapi-specs/content-watcher-service.json, backend/repositories/ContentRepository.ts, backend/services/ContentWatcherService.ts, backend/types/api.d.ts, backend/types/content-announcement/types.gen.ts, backend/types/openapi-content-watcher-service.d.ts
This PR changes from resetting the `content-watcher` scan at startup to requesting a targeted historical content search. It also incorporates updated generated types from content-watcher OpenAPI docs.
=> fix: initiate search for content at startup instead of resetting scan

backend/controllers/WebhookController.ts, backend/dev.Dockerfile, backend/index.ts, backend/package-lock.json, backend/package.json, backend/repositories/ContentRepository.ts, backend/services/feed.ts, backend/types/types.ts, docker-compose.yaml, frontend/src/content/PostList.tsx, start-gateway.sh, stop-gateway.sh
The goal of this PR is to store announced chain content received from content-watcher in a persistence layer instead of just an in-memory cache, so that on subsequent restarts the SAT backend doesn't have to wait to ask content-watcher to search the chain for all the content it wants.
Also, using SQLite as the persistence layer makes it easier to store/query replies associated with primary posts.
TODO:
=> feat: first pass at adding persistence to announced content

frontend/src/content/PostList.tsx
The goal of this PR is to not have the feeds go blank when a new post is posted and the spinner stops
Closes #118 
Figure out what is causing this and fix it.
* removed trigger from a use effect that was causing a render loop
1. login
2. create post
3. go to any of the feeds
4. create another post
5. wait for spinner to finish and check that posts are all still there, not an empty feed when there shouldn't be.
=> remove trigger from postlist useeffect

backend/openapi-specs/graph-service-webhook.yaml, backend/repositories/ContentRepository.ts, backend/services/feed.ts
This PR adds a filter option when retrieving posts so that only replies for the current post are retrieved (previously was retrieving all repliese for all posts, for each post)
Closes #122
=> fix: filter replies by parent content hash when retrieving posts

frontend/src/features/BroadcastInfo/PostHashDropdown.tsx, frontend/src/helpers/dsnp.ts, frontend/src/types.ts
The goal of this PR is to rename content hash from `HexString` to `Base32EncodedHash` to show its type to dev for future hash related use cases
=> update naming inline with dsnp spec hash

backend/docker-compose-bare-metal.yaml, docker-compose-local.yaml, docker-compose.yaml, start-gateway.sh, stop-gateway.sh
The goal of this PR is finish integrating the WEBHOOK_BASE_URL change for account service and update `start-gateway.sh` to allow for easily testing with locally built docker container images.
SAT environment variables need to be updated for a new `account-service` container image.
`start-gateway.sh` is updated with some bug fixes and an additional environment variable to use local docker images instead of pulling from docker hub. 
- Update `docker-compose.yaml` environment variables to be correct for the account service change to using `WEBHOOK_BASE_URL`
- Fixed a typo in `docker-compose-bare-metal.yaml` [this probably requires more testing which is out of scope for v1.0]
- Add `docker-compose-local.yaml` docker override file to allow using locally built docker images.
- …
=> chore: Update Docker Compose files for WEBHOOK_BASE_URL and start-gateway.sh updates

docker-compose.yaml, start-gateway.sh
This PR adds a prompt to `./start-gateway.sh` that allows the user to override the default `latest` tag for the Docker images with a specific tag of their choosing.
=> feat: add DOCKER_TAG as a configurable parameter in startup of services

docker-compose.yaml, frontend/src/features/Header/Header.tsx, start.sh, stop.sh
To make demos clearer and slightly more custom, lets add some basic customization options to the startup script:
Closes #151 
The `start.sh` script should ask a few questions, save the values in the env file and make sure that those values are passed through to the docker environment and correctly processed by the frontend to change the display.
- Updated `start.sh` to ask for name to appear in header and background color
- Updated `stop.sh` to match `start.sh` updates
- Updated `header.tsx` to get the name and color values from the environment
- Updated `docker-compose.yaml` to pass through the env values
- Add code to redact sensitive values when displaying the env file
- Add code to hide the input of sensitive values
1. Use `start.sh` and start from scratch to create a new env file by …
=> UI Customization Options in Startup script

backend/repositories/ContentRepository.ts, backend/services/ContentService.ts, backend/services/feed.ts, stop.sh
- When fetching content for (a) specific msaId(s), use the SQL query parameters to retrieve the appropriate results, instead of fetching content for all MSAs and then filtering the result.
- Small fix to `stop.sh` to work properly with non-default named projects (ie, when invoked with `-n <name>`)
Closes #157
=> fix: only fetch content in which we are interested from DB, instead of filtering results after

bash_functions.sh, docker-compose.local-ipfs.yaml, docker-compose.yaml, start.sh, stop.sh
A little code golf for readability and simplification.
Feature adds:
- "-s|--skip-setup" option allows re-running `start.sh` without re-running chain setup (useful in development cycles)
- extract out shell functions to a separate file so the overall script is easier to read (also can be reused in start & stop)
- Most branch logic is now done in the prompt parsing; we no longer need to branch on the values saved in the ENV_FILE if we read it in
=> feat: script simplification & readability

bash_functions.sh, docker-compose.local-ipfs.yaml, docker-compose.yaml, docs/post-flow.mmd, start.sh, stop.sh
The goal of this PR is allow users to select a subset of services to launch.
Updated `./start.sh` to ask whether each service should be started. Those answers are parsed and passed to the `docker compose` command. The values are also saved in the saved env file.
1. Execute `./start.sh` 
2. When asked whether or not to start a service, answer anything other than "y", e.g. "n".
3. Verify that the excluded services are not started.
Note: frontend and backend have dependencies on all the other services, so if one of those are yes, all the rest must also be yes.
=> Feature: Add the ability to selectively start services

start.sh
This PR ensures that the local `ipfs` container service is started when appropriate.
=> fix: make sure local ipfs is started when appropriate

bash_functions.sh, docker-compose.yaml, start.sh
The goal of this PR is update the Docker tooling for spinning up Gateway services to match Gateway v1.0.3
=> fix: update docker-compose for new gateway images

backend/docker-compose-bare-metal.yaml, backend/docker-compose.yaml, backend/environment/env.social-app-backend.template, docker-compose.yaml
The goal of this PR is to update SAT to use the newer versioned SIWF URLs.
See https://github.com/ProjectLibertyLabs/siwf/pull/172 for details
(Yes it will work either way)
=> Update to use the versioned URL for SIWF

backend/controllers/AuthController.ts, backend/openapi-specs/account.openapi.json, backend/openapi-specs/content-watcher.openapi.json, backend/openapi.json, backend/services/AccountService.ts, backend/types/api.d.ts, backend/types/openapi-account-service.d.ts, docker-compose.yaml, frontend/src/dsnpLink.ts, frontend/src/features/Login/Login.tsx, frontend/src/features/Login/LoginForm.tsx, frontend/src/pages/App/App.tsx, frontend/src/pages/Callback/Callback.tsx, frontend/src/pages/PageRoutes.tsx, package-lock.json
Introduces support for sign-in and sign-up using SIWF V2.
This update enables apps to onboard users with familiar login methods,
allowing users to authenticate with either their email or phone number,
bridging the experience for web2 users.
- Implemented backend routes to support the SIWF V2 flow
- Add a frontend button to navigate users to login with SIWF
- Created a callback page view to display account creation
Closes #170
=> feat(siwf): add siwf v2

docker-compose.yaml, start.sh
The goal of this PR is to allow social-app-template to work with gateway containers v1.4.0
Update `SIWF_V2_DOMAIN` to `SIWF_V2_URI_VALIDATION` in `docker-compose.yaml`
1. Remove existing gateway containers from docker desktop or your preferred container service.
2. Execute `start.sh` and verify that social-app-template runs with the new containers.
=> fix: update for gateway 1.4.0

bash_functions.sh, docker-compose.yaml
To fix https://github.com/ProjectLibertyLabs/social-app-template/issues/185
Also made it so when run in WSL that it can be accessed on LAN for localized testing in case the frequency node is not local to the host device.
=> fix: start.sh support for ubuntu. Also for quick WSL tests
